# Generated by Django 4.2 on 2025-02-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_attendance_comment_impression_reply_trip_tripimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
