# Generated by Django 4.2 on 2025-03-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_birthdaygreeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Yosh'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Elektron pochta'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='To‘liq ismi'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Profil rasmi'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('teacher', 'O‘qituvchi'), ('student', 'Talaba')], max_length=20, verbose_name='Roli'),
        ),
    ]
